# Generated by Django 4.2.30 on 2026-06-15 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('repeat_customers', models.IntegerField(default=0)),
                ('customer_retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_vendors', models.IntegerField(default=0)),
                ('new_vendors', models.IntegerField(default=0)),
                ('active_vendors', models.IntegerField(default=0)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monthly_metrics',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(db_index=True, unique=True)),
                ('week_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weekly_metrics',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('new_vendors', models.IntegerField(default=0)),
                ('active_vendors', models.IntegerField(default=0)),
                ('pending_vendors', models.IntegerField(default=0)),
                ('new_restaurants', models.IntegerField(default=0)),
                ('active_restaurants', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('avg_delivery_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending_orders', models.IntegerField(default=0)),
                ('accepted_orders', models.IntegerField(default=0)),
                ('preparing_orders', models.IntegerField(default=0)),
                ('ready_orders', models.IntegerField(default=0)),
                ('picked_up_orders', models.IntegerField(default=0)),
                ('out_for_delivery_orders', models.IntegerField(default=0)),
                ('delivered_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='daily_metri_date_07dd2d_idx'), models.Index(fields=['-total_revenue'], name='daily_metri_total_r_fdbccb_idx'), models.Index(fields=['-total_orders'], name='daily_metri_total_o_fa0472_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'), models.Index(fields=['action', '-created_at'], name='user_activi_action_5db802_idx'), models.Index(fields=['created_at'], name='user_activi_created_d4cab2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('purchase', 'Purchase'), ('login', 'Login'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('view_product', 'View Product'), ('checkout_start', 'Checkout Start'), ('checkout_complete', 'Checkout Complete')], db_index=True, max_length=50)),
                ('page_url', models.TextField()),
                ('referrer', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='analytics_e_event_t_bc280b_idx'), models.Index(fields=['user', '-created_at'], name='analytics_e_user_id_e1a457_idx'), models.Index(fields=['session_id', '-created_at'], name='analytics_e_session_c88a44_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx')],
            },
        ),
    ]
