# Generated by Django 4.2.30 on 2026-06-23 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('WEEKDAY', 'Weekday Offer'), ('WEEKEND', 'Weekend Offer'), ('SPECIAL', 'Special Offer'), ('FESTIVE', 'Festive Offer'), ('HAPPY_HOUR', 'Happy Hour'), ('BIRTHDAY', 'Birthday Special')], max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dining_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiningPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FLASH_SALE', 'Flash Sale'), ('FESTIVE', 'Festive Offer'), ('LOYALTY', 'Loyalty Program'), ('REFERRAL', 'Referral Offer'), ('NEW_USER', 'New User Offer')], max_length=20)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], max_length=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dining_promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.IntegerField(default=2)),
                ('special_requests', models.TextField(blank=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('booking_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurant_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_spicy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_reservations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ambiance',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Dining'), ('FINE', 'Fine Dining'), ('ROOFTOP', 'Rooftop'), ('CAFE', 'Cafe'), ('FAMILY', 'Family Dining'), ('FAST_CASUAL', 'Fast Casual'), ('BUFFET', 'Buffet'), ('BAR', 'Bar & Grill')], default='CASUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dress_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_booking_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_dining',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_live_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_private_dining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_delivery_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_takeaway_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='music_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='outdoor_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating_capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='serves_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='special_diets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wifi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantoffer',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantoffer',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantoffer',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Items'), ('CATEGORY', 'Category'), ('ITEM', 'Specific Item'), ('DINING', 'Dining Only'), ('DELIVERY', 'Delivery Only')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantoffer',
            name='time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='dining_experience',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurantoffer',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('BOGO', 'Buy One Get One'), ('COMBO', 'Combo Deal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('customer', 'restaurant')},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available'], name='menu_items_restaur_d2ad1f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'category'], name='menu_items_restaur_c683e9_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['has_dining', 'is_active', 'status'], name='restaurants_has_din_01080f_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'cuisine_type'], name='restaurants_city_043837_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_veg', 'serves_alcohol'], name='restaurants_is_veg_680be8_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantoffer',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurant__restaur_e6d3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantoffer',
            index=models.Index(fields=['valid_from', 'valid_to'], name='restaurant__valid_f_836ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['restaurant', '-created_at'], name='restaurant__restaur_1d5199_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantreview',
            index=models.Index(fields=['customer', 'restaurant'], name='restaurant__custome_26a499_idx'),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='diningpromotion',
            name='applicable_restaurants',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_offers', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='restaurantbooking',
            index=models.Index(fields=['restaurant', 'date', 'status'], name='restaurant__restaur_421688_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantbooking',
            index=models.Index(fields=['customer'], name='restaurant__custome_353313_idx'),
        ),
    ]
